#   THIS IS A SAPERATE IMPLEMENTATION OF THE STRING CLASS USING PURE PYTHON
#   THE STRUCTURE AND LOGIC OF THIS IS SIMILAR TO JAVA WHERE THE BASE IS CHARACTERS 
#   AND STRING IS BUILT FROM THERE. FOR THE SAKE OF KEEPING PYTHON ENVIRONMENT PURE
#   DO NOT IMPORT THIS TO OTHER PROJECTS.
